name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "18.1.0"
      - name: install dependencies
        working-directory: ./client
        run: yarn install
      - name: start build
        working-directory: ./client
        run: yarn build
